GRANT ALL PRIVILEGES ON *.* TO 'uberuser'@'%' IDENTIFIED BY PASSWORD '*ED41993E4AAA8C3E890B6730C79FBB2FF0160D9E';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `uberUniUlm`.* TO 'uberuser'@'%' WITH GRANT OPTION;
